version: '2'
services:
  zookeeper:
    container_name: kafka_zookeeper 
    image: washpost/zookeeper:3.4.9
    ports:
      - "8181:8181"
      - "2181:2181"
      - "3888:3888"
      - "2888:2888"
    environment:
      CLUSTER_SIZE: 1
      CONFIG_TYPE: file
  kafka:
    build: .
    ports:
      - "9092:9092"
      - "127.0.0.1:9999:9999"
    environment:
      REPL_FACTOR: 1
      BROKER_ID: 1
      INSTANCE_IP: 127.0.0.1
      ZOOKEEPER: zookeeper:2181/local
      LOG_MESSAGE_FORMAT_VERSION: 0.9.0 
      DEFAULT_REPLICATION_FACTOR: 1
    links:
      - zookeeper
